#pragma once

#include "game/Inventory.h"
#include "world/Block.h"

#include <array>
#include <initializer_list>
#include <string>
#include <utility>
#include <vector>

namespace mc {

class BlockRegistry;

// Crafting recipes, vanilla semantics: shaped patterns match anywhere in the grid
// (horizontally mirrored too), shapeless recipes match any arrangement.
//
// Ingredients are either a specific block name ("cobblestone") or a block TAG
// ("#planks" = any block the registry tagged "planks", mixed woods allowed — see
// BlockRegistry::withTag / Properties::tag). Recipe families are generated by
// iterating tags (every "#logs" member gets its log->planks recipe, every "#planks"
// member its slab/stairs/door recipes), so new blocks join the book just by carrying
// the tag. Unknown names/empty tags drop the recipe silently: furnace/chest recipes
// are pre-registered and activate the day those blocks exist. Non-block items
// (sticks, tools) join once an item registry exists.
class RecipeBook {
public:
    void registerDefaults(const BlockRegistry& reg);

    // grid = gw*gh ids row-major (AIR = empty cell). Empty stack = no match.
    ItemStack match(const BlockId* grid, int gw, int gh) const;

private:
    // One pattern cell / shapeless entry: a specific block or any member of a tag.
    struct Ingredient {
        BlockId id = BLOCK_AIR;     // specific block (when anyOf is empty)
        std::vector<BlockId> anyOf; // tag members (when built from "#tag")
        bool isEmpty() const { return id == BLOCK_AIR && anyOf.empty(); }
        bool matches(BlockId g) const {
            if (g == BLOCK_AIR) return isEmpty();
            if (!anyOf.empty()) return std::find(anyOf.begin(), anyOf.end(), g) != anyOf.end();
            return g == id;
        }
    };
    struct Recipe {
        bool shapeless = false;
        int w = 0, h = 0;                  // shaped pattern size
        std::array<Ingredient, 9> cells{}; // shaped ingredients row-major
        std::vector<Ingredient> loose;     // shapeless ingredients
        BlockId result = BLOCK_AIR;
        int count = 1;
    };
    std::vector<Recipe> recipes_;

    // "name" -> specific block, "#tag" -> any member. false = unknown (drop recipe).
    static bool resolve(const BlockRegistry& reg, const char* name, Ingredient& out);

    // Vanilla-style shaped pattern: rows of key characters (' ' = empty), e.g.
    // {"##", "##"} with key {{'#', "#planks"}}. Skipped if anything is unknown.
    void addShaped(const BlockRegistry& reg, std::initializer_list<const char*> rows,
                   const char* result, int count,
                   std::initializer_list<std::pair<char, const char*>> key);
    void addShapeless(const BlockRegistry& reg,
                      std::initializer_list<const char*> ingredients, const char* result,
                      int count);
};

} // namespace mc
